import { ArtisanProfile, Order, ProductListing, AnalyticsMetrics } from '../types';

export const INITIAL_ARTISAN: ArtisanProfile = {
  id: 'artisan_001',
  name: 'Ramvati Devi',
  phone: '+91 98765 43210',
  village: 'Naurangabad, Gorakhpur',
  state: 'Uttar Pradesh',
  craftType: 'Terracotta Pottery & Clay Sculpting',
  experienceYears: 24,
  language: 'en',
  avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
  totalEarnings: 48600,
  activeListingsCount: 5,
  totalOrdersCount: 28,
  rating: 4.9,
  verified: true,
  createdAt: '2025-01-15T10:00:00Z',
};

export const INITIAL_PRODUCTS: ProductListing[] = [
  {
    id: 'prod_101',
    artisanId: 'artisan_001',
    artisanName: 'Ramvati Devi',
    artisanCraft: 'Terracotta Pottery',
    artisanVillage: 'Gorakhpur',
    artisanState: 'Uttar Pradesh',
    originalLanguage: 'hi',
    rawVoiceTranscript: 'यह मिट्टी का बड़ा फूलदान मैंने कुम्हार के चाक पर हाथ से बनाया है, इस पर प्राकृतिक बेल-बूटे उकेरे गए हैं और यह पारंपरिक भट्टी में पका है।',
    rawPhotoUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=600&q=80',
    studioPhotoUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=85',
    imageEnhanced: true,
    title: 'Handcrafted Gorakhpur Terracotta Floral Artisan Vase',
    seoTitle: 'Authentic Handcrafted GI Tag Gorakhpur Terracotta Vase | Natural Clay Home Decor',
    description: 'Masterfully sculpted by veteran artisan Ramvati Devi using riverbed silt and fired in open-hearth firewood kilns. Features intricate floral relief carvings done entirely by bamboo needles.',
    culturalStory: 'Gorakhpur terracotta is an ancient heritage craft holding prestigious Geographical Indication (GI) status. Passed down through 4 generations in Naurangabad, every piece breathes natural porous clay that keeps spaces cool and earthy.',
    craftTechnique: 'Wheel-thrown clay, bamboo tool sculpting, natural pit firing',
    materials: ['Natural Alluvial Clay', 'Iron Ore Red Slip (Kabis)', 'Organic Wood Ash'],
    dimensions: '14" Height x 7" Diameter, 1.8 kg',
    careInstructions: 'Wipe with dry microfiber cloth. Avoid water soak.',
    tags: ['Terracotta', 'GI Tag Craft', 'Vase', 'Sustainable', 'Home Decor', 'Gorakhpur'],
    giTagStatus: 'GI Tag Certified (GI-614)',
    artisanPrice: 850,
    suggestedMarketPrice: 1450,
    retailPrice: 1299,
    estimatedMarginPercent: 82,
    competitorAveragePrice: 1650,
    marketPriceBenchmark: {
      low: 1100,
      median: 1450,
      high: 1850,
      platformComparisons: [
        { platform: 'Fabindia Heritage Store', price: 1750 },
        { platform: 'Amazon Karigar Hub', price: 1499 },
        { platform: 'ONDC Crafts Network', price: 1250 },
        { platform: 'Urban Handicrafts Export', price: 1950 },
      ],
    },
    stockQuantity: 14,
    status: 'published',
    views: 420,
    ordersCount: 18,
    createdAt: '2025-02-01T08:30:00Z',
  },
  {
    id: 'prod_102',
    artisanId: 'artisan_001',
    artisanName: 'Ramvati Devi',
    artisanCraft: 'Terracotta Pottery',
    artisanVillage: 'Gorakhpur',
    artisanState: 'Uttar Pradesh',
    originalLanguage: 'hi',
    rawVoiceTranscript: 'दीपावली और पूजा के लिए पांच मुख वाला अखंड दीया, मिट्टी को छानकर धूप में सुखाकर बनाया है।',
    rawPhotoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    studioPhotoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=85',
    imageEnhanced: true,
    title: 'Heritage Panch-Mukhi Terracotta Ritual Diya Lamp',
    seoTitle: 'Traditional 5-Wick Clay Diya | Hand-sculpted Terracotta Oil Lamp for Festive Decor',
    description: 'Hand-pressed auspicious Panch-Mukhi (5-wick) oil lamp crafted from mineral-rich clay. Holds oil without seepage and glows with serene festive warmth.',
    culturalStory: 'Ritual clay lamps symbolize victory of light over ignorance. In Uttar Pradesh, potter families sculpt these sacred lamps during Kartik month following ancient Vedic pottery forms.',
    craftTechnique: 'Hand molding and kiln baking',
    materials: ['Unrefined Red Clay', 'Natural Ochre pigment'],
    dimensions: '6" Diameter x 3" Height, 450 g',
    careInstructions: 'Clean gently with mild warm water after ritual oil usage.',
    tags: ['Diya', 'Pooja Decor', 'Festive', 'Clay Lamp', 'Eco Friendly'],
    giTagStatus: 'GI Tag Verified',
    artisanPrice: 280,
    suggestedMarketPrice: 550,
    retailPrice: 499,
    estimatedMarginPercent: 85,
    competitorAveragePrice: 590,
    marketPriceBenchmark: {
      low: 450,
      median: 550,
      high: 699,
      platformComparisons: [
        { platform: 'Amazon Karigar', price: 549 },
        { platform: 'Pepperfry Handmade', price: 620 },
        { platform: 'Direct ONDC', price: 480 },
      ],
    },
    stockQuantity: 42,
    status: 'published',
    views: 680,
    ordersCount: 34,
    createdAt: '2025-02-10T11:20:00Z',
  },
  {
    id: 'prod_103',
    artisanId: 'artisan_001',
    artisanName: 'Balamurugan K',
    artisanCraft: 'Pattamadai Mat Weaving',
    artisanVillage: 'Pattamadai, Tirunelveli',
    artisanState: 'Tamil Nadu',
    originalLanguage: 'ta',
    rawVoiceTranscript: 'இந்த கோரைப்பாய் தாமிரபரணி ஆற்று படுக்கையில் வளரும் புல்லால் நெய்யப்பட்டது. மிக மென்மையான பட்டு போன்ற பாய்.',
    rawPhotoUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=600&q=80',
    studioPhotoUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=85',
    imageEnhanced: true,
    title: 'GI Pattamadai Korai Pai Ultra-Fine Silk Sleeping Mat',
    seoTitle: 'Authentic Pattamadai Fine River Grass Mat | Handwoven Eco-Friendly Yoga & Sleep Mat',
    description: 'Woven with 140-count ultra-fine Korai reeds harvested from the banks of river Thamirabarani. Naturally temperature regulating and foldable like pure fabric.',
    culturalStory: 'Pattamadai mats have won royal honors since the 19th century and are traditionally presented at auspicious South Indian weddings as symbols of harmony and wellness.',
    craftTechnique: 'Split grass soaking, fine frame handloom weaving',
    materials: ['Korai River Grass', 'Organic Cotton Warp', 'Turmeric Natural Dye'],
    dimensions: '6 ft Length x 3.5 ft Width, 1.2 kg',
    careInstructions: 'Sun dry periodically. Roll gently after use.',
    tags: ['Pattamadai', 'Korai Mat', 'Tamil Nadu Craft', 'GI Tag', 'Yoga Mat'],
    giTagStatus: 'GI Tag Certified (GI-138)',
    artisanPrice: 1200,
    suggestedMarketPrice: 2400,
    retailPrice: 2199,
    estimatedMarginPercent: 78,
    competitorAveragePrice: 2600,
    marketPriceBenchmark: {
      low: 1800,
      median: 2350,
      high: 2900,
      platformComparisons: [
        { platform: 'Co-optex Artisan', price: 2300 },
        { platform: 'Etsy Global India', price: 2850 },
        { platform: 'Fabindia Craft', price: 2600 },
      ],
    },
    stockQuantity: 4,
    status: 'low_stock',
    views: 310,
    ordersCount: 9,
    createdAt: '2025-02-18T14:45:00Z',
  },
];

// -----------------------------------------------------------------------
// MARKETPLACE_PRODUCTS: multi-artisan product pool shown to Buyers.
// Includes artisans from different states to simulate a real marketplace.
// -----------------------------------------------------------------------
export const MARKETPLACE_PRODUCTS: ProductListing[] = [
  // Include the seller's own listed products as part of the marketplace
  ...INITIAL_PRODUCTS,

  // Additional marketplace products from other artisans across India
  {
    id: 'mkt_201',
    artisanId: 'artisan_002',
    artisanName: 'Lakshmi Bai',
    artisanCraft: 'Madhubani Painting',
    artisanVillage: 'Madhubani, Mithila',
    artisanState: 'Bihar',
    originalLanguage: 'hi',
    rawVoiceTranscript: 'यह मधुबनी पेंटिंग मैंने प्राकृतिक रंगों से बनाई है, इसमें मछली और कमल की पारंपरिक रचना है।',
    rawPhotoUrl: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=600&q=80',
    studioPhotoUrl: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=800&q=85',
    imageEnhanced: true,
    title: 'Traditional Madhubani Mithila Fish & Lotus Painting',
    seoTitle: 'Authentic Madhubani Painting Bihar | GI Tag Mithila Folk Art on Handmade Paper',
    description: 'Hand-painted with natural mineral pigments on handmade paper. Features the iconic Mithila fish-and-lotus motif symbolizing prosperity and harmony.',
    culturalStory: 'Madhubani (Mithila) painting is a 2,500-year-old folk art from Bihar, traditionally painted by women on freshly plastered mud walls during festivals.',
    craftTechnique: 'Natural mineral pigments, bamboo pen, handmade paper',
    materials: ['Handmade Lokta Paper', 'Natural Mineral Pigments', 'Cow-dung paste primer'],
    dimensions: '24" x 18", 180 g',
    careInstructions: 'Frame under UV-protected glass. Avoid direct sunlight.',
    tags: ['Madhubani', 'Mithila', 'GI Tag Art', 'Folk Painting', 'Bihar Craft'],
    giTagStatus: 'GI Tag Certified (GI-590)',
    artisanPrice: 700,
    suggestedMarketPrice: 1600,
    retailPrice: 1399,
    estimatedMarginPercent: 80,
    competitorAveragePrice: 1800,
    marketPriceBenchmark: {
      low: 1200, median: 1600, high: 2100,
      platformComparisons: [
        { platform: 'Dilli Haat', price: 1800 },
        { platform: 'Etsy India', price: 2100 },
      ],
    },
    stockQuantity: 8,
    status: 'published',
    views: 520,
    ordersCount: 14,
    createdAt: '2025-03-05T09:00:00Z',
  },
  {
    id: 'mkt_202',
    artisanId: 'artisan_003',
    artisanName: 'Murugesan S',
    artisanCraft: 'Tanjore Painting',
    artisanVillage: 'Thanjavur',
    artisanState: 'Tamil Nadu',
    originalLanguage: 'ta',
    rawVoiceTranscript: 'இந்த தஞ்சாவூர் ஓவியம் தங்க வேலையுடன் செய்யப்பட்டது, இதில் பாலகிருஷ்ணன் சிலை உள்ளது.',
    rawPhotoUrl: 'https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=600&q=80',
    studioPhotoUrl: 'https://images.unsplash.com/photo-1582845512747-e42001c95638?auto=format&fit=crop&w=800&q=85',
    imageEnhanced: true,
    title: 'Tanjore Bal Krishna Gold-Leaf Panel Painting',
    seoTitle: 'Authentic Thanjavur Tanjore Painting with 24K Gold Leaf | South Indian Temple Art',
    description: 'Exquisite Tanjore panel featuring Bal Krishna in dancing pose, embellished with 24K gold leaf, semi-precious stones, and natural gesso. A museum-quality heirloom.',
    culturalStory: 'Thanjavur (Tanjore) paintings originated in the 16th century Nayaka court. Famous for their gold-foil work, vivid colors, and ornate deity compositions.',
    craftTechnique: '24K gold leaf application, gesso relief, semi-precious stone inlay',
    materials: ['Teak Wood Panel', '24K Gold Leaf', 'Semiprecious Stones', 'Natural Gesso'],
    dimensions: '12" x 10" Panel, 900 g',
    careInstructions: 'Dry dust only. Keep away from moisture and direct sunlight.',
    tags: ['Tanjore', 'Thanjavur', 'Gold Leaf', 'Temple Art', 'Tamil Nadu Craft'],
    giTagStatus: 'GI Tag Certified (GI-262)',
    artisanPrice: 2800,
    suggestedMarketPrice: 6500,
    retailPrice: 5499,
    estimatedMarginPercent: 76,
    competitorAveragePrice: 7000,
    marketPriceBenchmark: {
      low: 4500, median: 6000, high: 8500,
      platformComparisons: [
        { platform: 'Craftsvilla', price: 6800 },
        { platform: 'Amazon Handmade', price: 5999 },
      ],
    },
    stockQuantity: 3,
    status: 'low_stock',
    views: 890,
    ordersCount: 7,
    createdAt: '2025-03-10T12:00:00Z',
  },
  {
    id: 'mkt_203',
    artisanId: 'artisan_004',
    artisanName: 'Gita Devi',
    artisanCraft: 'Warli Tribal Painting',
    artisanVillage: 'Dahanu, Palghar',
    artisanState: 'Maharashtra',
    originalLanguage: 'mr',
    rawVoiceTranscript: 'हे वारली चित्र मी भाताच्या पेस्टने बांबू काठीने काढले आहे, त्यात आदिवासी नृत्य दाखवले आहे.',
    rawPhotoUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    studioPhotoUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=85',
    imageEnhanced: true,
    title: 'Warli Tribal Harvest Dance Painting on Handmade Canvas',
    seoTitle: 'Authentic Warli Tribal Art Maharashtra | Folk Dance Festival Painting on Canvas',
    description: 'Traditional geometric Warli art depicting the Tarpa harvest festival dance. Painted with rice-paste on handmade cotton canvas using bamboo sticks.',
    culturalStory: 'Warli art is one of the oldest art traditions in India, over 2,500 years old, practiced by the Warli tribe of Maharashtra\'s Sahyadri hills as ritual storytelling.',
    craftTechnique: 'Rice paste painting, bamboo pen on cotton canvas',
    materials: ['Handmade Cotton Canvas', 'Rice Paste Pigment', 'Bamboo Stick Pen'],
    dimensions: '20" x 16" Canvas, 250 g',
    careInstructions: 'Frame under glass. Keep dry.',
    tags: ['Warli', 'Tribal Art', 'Maharashtra Craft', 'Folk Art', 'Canvas Painting'],
    giTagStatus: 'Authentic Tribal Craft',
    artisanPrice: 450,
    suggestedMarketPrice: 1100,
    retailPrice: 899,
    estimatedMarginPercent: 78,
    competitorAveragePrice: 1200,
    marketPriceBenchmark: {
      low: 700, median: 1000, high: 1400,
      platformComparisons: [
        { platform: 'Tribemart', price: 1100 },
        { platform: 'Flipkart Handmade', price: 950 },
      ],
    },
    stockQuantity: 12,
    status: 'published',
    views: 340,
    ordersCount: 11,
    createdAt: '2025-03-14T10:30:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_901',
    orderNumber: 'TULIP-84920',
    productId: 'prod_101',
    productTitle: 'Handcrafted Gorakhpur Terracotta Floral Artisan Vase',
    productImageUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=400&q=80',
    artisanId: 'artisan_001',
    artisanName: 'Ramvati Devi',
    buyerName: 'Ananya Sharma',
    buyerCity: 'Bengaluru',
    buyerState: 'Karnataka',
    amount: 1299,
    artisanEarnings: 1143,
    platformFee: 156,
    status: 'pending',
    createdAt: '2025-03-01T09:15:00Z',
    shippingAddress: 'Flat 402, Green Glen Layout, Bellandur, Bengaluru 560103',
    paymentMethod: 'UPI (PhonePe / GPay)',
  },
  {
    id: 'ord_902',
    orderNumber: 'TULIP-84918',
    productId: 'prod_102',
    productTitle: 'Heritage Panch-Mukhi Terracotta Ritual Diya Lamp',
    productImageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
    artisanId: 'artisan_001',
    artisanName: 'Ramvati Devi',
    buyerName: 'Vikram Joshi',
    buyerCity: 'Pune',
    buyerState: 'Maharashtra',
    amount: 499,
    artisanEarnings: 439,
    platformFee: 60,
    status: 'fulfilled',
    createdAt: '2025-02-28T16:30:00Z',
    shippingAddress: 'Plot 12, Baner Pashan Link Rd, Pune 411045',
    paymentMethod: 'Credit Card',
  },
  {
    id: 'ord_903',
    orderNumber: 'TULIP-84912',
    productId: 'prod_101',
    productTitle: 'Handcrafted Gorakhpur Terracotta Floral Artisan Vase',
    productImageUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=400&q=80',
    artisanId: 'artisan_001',
    artisanName: 'Ramvati Devi',
    buyerName: 'Pooja Nair',
    buyerCity: 'Kochi',
    buyerState: 'Kerala',
    amount: 1299,
    artisanEarnings: 1143,
    platformFee: 156,
    status: 'fulfilled',
    createdAt: '2025-02-27T11:00:00Z',
    shippingAddress: 'Marine Drive Residences, Kochi 682011',
    paymentMethod: 'UPI',
  },
  {
    id: 'ord_904',
    orderNumber: 'TULIP-84905',
    productId: 'prod_103',
    productTitle: 'GI Pattamadai Korai Pai Ultra-Fine Silk Sleeping Mat',
    productImageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80',
    artisanId: 'artisan_001',
    artisanName: 'Ramvati Devi',
    buyerName: 'Rahul Mehta',
    buyerCity: 'Ahmedabad',
    buyerState: 'Gujarat',
    amount: 2199,
    artisanEarnings: 1935,
    platformFee: 264,
    status: 'canceled',
    createdAt: '2025-02-25T14:10:00Z',
    shippingAddress: 'B-201 Vastrapur, Ahmedabad 380015',
    paymentMethod: 'Cash on Delivery',
  },
];

export const INITIAL_ANALYTICS: AnalyticsMetrics = {
  totalSales: 54680,
  activeOrders: 4,
  totalRevenue: 62400,
  artisanEarnings: 48900,
  totalInventoryItems: 60,
  revenueTrends: [
    { day: 'Mon', sales: 4200, orders: 3 },
    { day: 'Tue', sales: 6800, orders: 5 },
    { day: 'Wed', sales: 8100, orders: 6 },
    { day: 'Thu', sales: 5400, orders: 4 },
    { day: 'Fri', sales: 11200, orders: 8 },
    { day: 'Sat', sales: 14500, orders: 11 },
    { day: 'Sun', sales: 12200, orders: 9 },
  ],
  craftCategoryDistribution: [
    { category: 'Terracotta Pottery', count: 2, revenue: 38400 },
    { category: 'Handloom & Mats', count: 1, revenue: 16280 },
  ],
  orderStatusDistribution: [
    { status: 'fulfilled', count: 22 },
    { status: 'pending', count: 4 },
    { status: 'canceled', count: 2 },
  ],
};
